import { Theme } from '@rainbow-me/rainbowkit';

export const liquidityVectorTheme: Theme = {
  blurs: {
    modalOverlay: 'blur(4px)',
  },
  colors: {
    accentColor: '#FF4D00',
    accentColorForeground: '#FFFFFF',
    actionButtonBorder: '#1A1A1A',
    actionButtonBorderMobile: '#1A1A1A',
    actionButtonSecondaryBackground: '#F9F7F5',
    closeButton: '#1A1A1A',
    closeButtonBackground: '#E5E0D8',
    connectButtonBackground: '#FF4D00',
    connectButtonBackgroundError: '#FF6B6B',
    connectButtonInnerBackground: '#FFFFFF',
    connectButtonText: '#1A1A1A',
    connectButtonTextError: '#FFFFFF',
    connectionIndicator: '#006B4C',
    downloadBottomCardBackground: '#E5E0D8',
    downloadTopCardBackground: '#1A1A1A',
    error: '#FF4D00',
    generalBorder: '#1A1A1A',
    generalBorderDim: 'rgba(26, 26, 26, 0.2)',
    menuItemBackground: '#E5E0D8',
    modalBackdrop: 'rgba(26, 26, 26, 0.4)',
    modalBackground: '#FFFFFF',
    modalBorder: '#1A1A1A',
    modalText: '#1A1A1A',
    modalTextDim: 'rgba(26, 26, 26, 0.5)',
    modalTextSecondary: 'rgba(26, 26, 26, 0.7)',
    profileAction: '#F9F7F5',
    profileActionHover: '#E5E0D8',
    profileForeground: '#F9F7F5',
    selectedOptionBorder: '#FF4D00',
    standby: '#1A1A1A',
  },
  fonts: {
    body: 'var(--font-inter), sans-serif',
  },
  radii: {
    actionButton: '8px',
    connectButton: '8px',
    menuButton: '8px',
    modal: '12px',
    modalMobile: '12px',
  },
  shadows: {
    connectButton: '3px 3px 0px 0px #1A1A1A',
    dialog: '6px 6px 0px 0px #1A1A1A',
    profileDetailsAction: '3px 3px 0px 0px #1A1A1A',
    selectedOption: '2px 2px 0px 0px #1A1A1A',
    selectedWallet: '2px 2px 0px 0px #1A1A1A',
    walletLogo: 'none',
  },
};
