import { Theme } from '@rainbow-me/rainbowkit';

export const liquidityVectorTheme: Theme = {
  blurs: {
    modalOverlay: 'blur(4px)',
  },
  colors: {
    accentColor: '#CCFF00',
    accentColorForeground: '#371E7B',
    actionButtonBorder: '#371E7B',
    actionButtonBorderMobile: '#371E7B',
    actionButtonSecondaryBackground: '#F9F9F5',
    closeButton: '#371E7B',
    closeButtonBackground: '#F9F9F5',
    connectButtonBackground: '#CCFF00',
    connectButtonBackgroundError: '#FF6B6B',
    connectButtonInnerBackground: '#F9F9F5',
    connectButtonText: '#371E7B',
    connectButtonTextError: '#FFFFFF',
    connectionIndicator: '#CCFF00',
    downloadBottomCardBackground: '#F9F9F5',
    downloadTopCardBackground: '#371E7B',
    error: '#FF6B6B',
    generalBorder: '#371E7B',
    generalBorderDim: 'rgba(55, 30, 123, 0.3)',
    menuItemBackground: '#F9F9F5',
    modalBackdrop: 'rgba(55, 30, 123, 0.4)',
    modalBackground: '#FFFFFF',
    modalBorder: '#371E7B',
    modalText: '#371E7B',
    modalTextDim: 'rgba(55, 30, 123, 0.7)',
    modalTextSecondary: 'rgba(55, 30, 123, 0.8)',
    profileAction: '#F9F9F5',
    profileActionHover: '#CCFF00',
    profileForeground: '#F9F9F5',
    selectedOptionBorder: '#CCFF00',
    standby: '#CCFF00',
  },
  fonts: {
    body: 'Inter, sans-serif',
  },
  radii: {
    actionButton: '0px',
    connectButton: '0px',
    menuButton: '0px',
    modal: '0px',
    modalMobile: '0px',
  },
  shadows: {
    connectButton: '4px 4px 0px 0px #371E7B',
    dialog: '8px 8px 0px 0px #371E7B',
    profileDetailsAction: '4px 4px 0px 0px #371E7B',
    selectedOption: '4px 4px 0px 0px #371E7B',
    selectedWallet: '4px 4px 0px 0px #371E7B',
    walletLogo: 'none',
  },
};
